debug: true
logging:
  level:
    root: info
    # 启动信息去掉不需要的 CONDITIONS EVALUATION REPORT
    org.springframework.boot.autoconfigure: ERROR

server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/second_kill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  # entity 扫描的包名
  type-aliases-package: com.csthink.secondkill.domain
  # Mapper.xml 所在的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000

test:
  name: 秒杀系统
  description: write code , make magic
  showAd: false
  productNum: 20